# Generated by Django 4.1.5 on 2023-02-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Certificacion')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtitulo Certificacion | Area')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='aboutm', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Edicion')),
            ],
            options={
                'verbose_name': 'certificacion',
                'verbose_name_plural': 'certificaciones',
                'ordering': ['-created'],
            },
        ),
    ]
