# Generated by Django 4.1.5 on 2023-02-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtitulo Servicio')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='Services', verbose_name='Imagen Ultimo Trabajo')),
                ('client', models.CharField(max_length=200, verbose_name='Cliente')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Edicion')),
            ],
            options={
                'verbose_name': 'inicio',
                'verbose_name_plural': 'inicios',
                'ordering': ['-created'],
            },
        ),
    ]
